[package]
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"
name = "test"
version = "0.1.0"

[dependencies]
mongodb = {version = "1.1.1", default-features = false, features = ["sync"]}
serde = "1.0.116"
serde_json = "1.0.57"

